---
title: "Semesterplan"
subtitle: "Methodenseminar"
date: 04/01/2024
date-modified: last-modified
date-format: "DD.MM.YYYY"
---

::: callout-note
Diese Seite erhält eine Übersicht über die Sitzung bzw. Themen des Methodenseminar im Sommersemester 2024. Bitte beachten Sie, dass die Inhalte des Kurses ({{< bi file-earmark-slides >}} Folien, {{< bi pencil-square >}} Exercises, {{< bi file-earmark-code >}} Showcases und {{< bi book >}} Hintergrundinformationen) im Laufe des Semesters stetig aktualisiert werden, wobei alle Änderungen hier dokumentiert werden.
:::

| Sitzung | Datum      | Thema                                    | Unterlagen                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|-----------------|-----------------|------------------|---------------------|
|         |            | **Introduction**                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 1       | 18.04.2024 | Einführung & Überblick                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|         | **📚**     | **Block I: Systematic Review**           |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 2       | 25.04.2024 | Einführung in Systematic Reviews I       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 3       | 02.05.2024 | Einführung in Systematic Reviews II      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|         | 09.05.2024 | 🏖️ *Feiertag*                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 4       | 16.05.2024 | Automatisierung von SRs & KI-Tools I     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|         | 23.05.2024 | 🍻 *WiSo-Projekt-Woche*                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|         | 30.05.2024 | 🏖️ *Feiertag*                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 5       | 04.06.2024 | 🍕 Gastvortrag: Prof. Dr. Emese Domahidi |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 6       | 06.06.2024 | Automatisierung von SRs & KI-Tools       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|         | **💻**     | **Block II: Text as Data**               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 7       | 13.06.2024 | Introduction to Text as Data             | [{{< bi file-earmark-slides >}}](/slides/ms-slides-07.html "Slides: Session 07"){aria-label="Slides Session 07"} \| [{{< bi pencil-square >}}](/exercises/ms-exercise-07_solution.html "Exercise: Session 07"){aria-label="Exercise Session 07"} \| [{{< bi file-earmark-code >}}](/exercises/ms-showcase-07.html "Showcase: Session 07"){aria-label="Showcase Session 07"} \| [{{< bi book >}}](/sessions/ms-session-07.html "Session 07"){aria-label="Session 07"} |
| 8       | 20.06.2024 | Text processing in R                          | [{{< bi file-earmark-slides >}}](/slides/ms-slides-08.html "Slides: Session 08"){aria-label="Slides Session 08"} \| [{{< bi pencil-square >}}](/exercises/ms-exercise-08.html "Exercise: Session 08"){aria-label="Exercise Session 08"} \| [{{< bi file-earmark-code >}}](/exercises/ms-showcase-08.html "Showcase: Session 08"){aria-label="Showcase Session 08"} \| [{{< bi book >}}](/sessions/ms-session-08.html "Session 08"){aria-label="Session 08"} |
| 9       | 27.06.2024 | Unsupervised Machine Learning I          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 10      | 04.07.2024 | Unsupervised Machine Learning II         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 11      | 11.07.2024 | Recap & Ausblick                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| 12      | 18.07.2024 | 🏁 Semesterabschluss                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

: {tbl-colwidths="\[2,20,55,20\]"}

```{r backup}
#| echo: false
knitr::knit_exit()
```

|      |      |       | Prepare | Slides | AE  |                                                    Labs                                                    | HW  | Exam | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic |   📖    |   🖥️   | 📋  | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️  |  ✅  |   📂    |

Icons

-   Preparation: {{< bi book >}}
-   Slides: {{< bi file-earmark-slides >}}
-   Group Activity: {{< iconify octicon comment-discussion-24 >}}
-   Application exercises: {{< iconify simple-icons googlecolab >}}